INSERT INTO users (name, email, password, role, created_at) VALUES
('Ayu Hartati', 'ayu@example.com', MD5('password123'), 'admin', NOW()),
('Rizky Pratama', 'rizky@example.com', MD5('password123'), 'user', NOW()),
('Siti Aminah', 'siti@example.com', MD5('password123'), 'user', NOW()),
('Budi Santoso', 'budi@example.com', MD5('password123'), 'admin', NOW()),
('Linda Sari', 'linda@example.com', MD5('password123'), 'user', NOW()),
('Agus Salim', 'agus@example.com', MD5('password123'), 'user', NOW()),
('Fitriani', 'fitri@example.com', MD5('password123'), 'admin', NOW()),
('Joko Susilo', 'joko@example.com', MD5('password123'), 'user', NOW()),
('Maya Putri', 'maya@example.com', MD5('password123'), 'user', NOW()),
('Eka Saputra', 'eka@example.com', MD5('password123'), 'user', NOW()),
('Nina Kusuma', 'nina@example.com', MD5('password123'), 'user', NOW()),
('Dedi Rahman', 'dedi@example.com', MD5('password123'), 'user', NOW()),
('Wulan Sari', 'wulan@example.com', MD5('password123'), 'admin', NOW()),
('Hendra Wijaya', 'hendra@example.com', MD5('password123'), 'user', NOW()),
('Tina Amelia', 'tina@example.com', MD5('password123'), 'user', NOW()),
('Bayu Nugraha', 'bayu@example.com', MD5('password123'), 'user', NOW()),
('Rina Marlina', 'rina@example.com', MD5('password123'), 'admin', NOW()),
('Fajar Sidik', 'fajar@example.com', MD5('password123'), 'user', NOW()),
('Anita Dewi', 'anita@example.com', MD5('password123'), 'user', NOW()),
('Yusuf Hidayat', 'yusuf@example.com', MD5('password123'), 'user', NOW());
